version: "3.7"
services:
  web:
    container_name: labelimgweb_dev
    build:
      context: ./web
      dockerfile: Docker/Dockerfile-dev
    ports:
    - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./web:/app
    tty: true   
    command: /bin/sh
    #command: /opt/conda/bin/python app.py
  db:
    container_name: labelimgweb_db
    build:
      context: ./db
      dockerfile: Docker/Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    container_name: labelimgweb_adminer
    image: adminer
    environment:
        ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080